import { Metadata } from 'next';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { Content } from 'antd/lib/layout/layout';
import Profile from './_component/Profile';
import RouteItem from './_component/RouteItem';
import fs from 'fs/promises';
import styles from './layout.module.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = async ({
  children,
}: Readonly<{ children: React.ReactNode }>) => {
  const subs = await fs.readdir(`${process.cwd()}/src/blog/`, {
    recursive: true,
  });
  const routePaths = subs
    .filter((item) => {
      return item.split('/').length != 1;
    })
    .map((item) => {
      const [type, id] = item.split('.')[0].split('/');
      return {
        type,
        id,
      };
    });

  return (
    <html>
      <body className={styles.Body}>
        <AntdRegistry>
          <div className={styles.Container}>
            <div className={styles.Header}>
              <div className={styles.HeaderEnd}>
                <Profile />
              </div>
            </div>
            <div className={styles.Content}>
              <div className={styles.Sider}>
                {routePaths.map((item, index) => (
                  <RouteItem
                    key={index}
                    path={`/blog/${item.type}/${item.id}`}
                    text={item.id}
                  />
                ))}
              </div>
              <Content>{children}</Content>
            </div>
          </div>
        </AntdRegistry>
      </body>
    </html>
  );
};

export default RootLayout;
