import { Metadata } from 'next';
import LayoutHeader from './_component/LayoutHeader';
import Providers from './providers';
import './globals.css';
import '@arco-design/web-react/dist/css/arco.css';
import { ROOT_PATH } from './const/constants';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: [
    {
      rel: 'icon',
      type: 'image/png',
      url: `${ROOT_PATH}/favicon.png`,
      sizes: '256x256',
    },
  ],
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang='en'>
      <body>
        <Providers>
          <LayoutHeader />
          {children}
        </Providers>
      </body>
    </html>
  );
};

export default RootLayout;
